spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dubbo_mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    solr:
      host: http://192.168.5.121:8080/solr
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: java2021717
    password: abc123
    virtual-host: /java2021
dubbo:
  protocol:
    name: dubbo
    port: 20881
  application:
    name: dbm-search-service
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  monitor:
    protocol: registry
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081

