server:
  port: 9090
  servlet:
    context-path: /
dubbo:
  protocol:
    name: dubbo
  application:
    name: dbm-background
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  monitor:
    protocol: registry
  consumer:
    timeout: 2000
    check: false
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
pagehelper:
  dialect: mysql
  reasonable: true
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.5.12:22122
file:
  upload-url: http://192.168.5.12:8888/

