server:
  port: 9090
  servlet:
    context-path: /
dubbo:
  protocol:
    name: dubbo
  application:
    name: dbm-background
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
#表示从注册中心发现监控中心地址，否则直连监控中心，没有启动监控中心的话就注释掉
#  monitor:
#    protocol: registry
  consumer:
    timeout: 2000
    check: false
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: java2021717
    password: abc123
    virtual-host: /java2021
pagehelper:
  dialect: mysql
  reasonable: true
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.5.12:22122
file:
  upload-url: http://192.168.5.12:8888/

